services:
    frontend:
        image: node:23-alpine
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        command: sh -c 'npm install && npm run dev -- --host'

    backend:
        build:
            context: ./backend
        working_dir: /app
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        environment:
            PORT: 8000
        command: composer start
