name: Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurando Node 23
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalando dependências
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Build
        run: npm run build
